######################################################################
# Automatically generated by qmake (2.00a) wto gru 26 18:40:35 2006
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += . src
INCLUDEPATH += .

# Input
SOURCES += src/pg_main.cpp
