######################################################################
# Automatically generated by qmake (2.00a) wto gru 26 18:52:53 2006
######################################################################

TEMPLATE = app
TARGET = ../bin/proc_gui
DEPENDPATH += . src src/ui
INCLUDEPATH += . src

OBJECTS_DIR = obj
MOC_DIR = src/moc
UI_DIR = src/ui

# Input
HEADERS += src/main_form.h
FORMS += src/ui/main_form.ui
SOURCES += src/main_form.cpp src/pg_main.cpp
