######################################################################
# Automatically generated by qmake (2.00a) wto gru 26 19:46:44 2006
######################################################################

TEMPLATE = app
TARGET = ../bin/processor
DEPENDPATH += . src
INCLUDEPATH += . src

OBJECTS_DIR = obj

# Input
HEADERS += src/p_parser.h src/p_output.h src/p_utils.h
SOURCES += src/p_main.cpp src/p_parser.cpp src/p_output.cpp src/p_utils.cpp
